Add support for wildcards in the map file #170
codekie/openapi-examples-validator pull request #172
Opened 2022-06-12 21:11 UTC by marc0l92

I'm using the function `glob.sync()` (that you already use to find the mapping file) to expand the wildcards in the path to the example inside the mapping files.

2022-06-13 10:08 UTC, codekie requested changes
Please also add at least one test case for invalid examples and make sure that then output for globbed paths is the same as with the non-globbed counterparts (the ordering of files can be disregarded).

2022-06-13 10:08 UTC, codekie commented on src/index.js
>                      filePathExample
Passing the original `filePathExample` here, will also result in the glob showing up in the error messages for invalid examples (instead of the full path to the example file), which isn't very helpful:

e.g.

```
        {
           "dataPath": ".versions[0]"
           "exampleFilePath": "test/data/v2/external-examples-invalid-*.json"
           "keyword": "required"
           "mapFilePath": "/tmp/openapi-examples-validator/test/data/v2/map-external-examples-glob-invalid1.json"
           "message": "should have required property 'links'"
           "params": {
           "type": "Validation"
         }
```

`exampleFilePath` in the error-message should contain the expanded path to the invalid example file (e.g. `test/data/v2/external-examples-invalid-missing-link.json` in this case)

2022-06-13 19:22 UTC, marc0l92 commented
> Please also add at least one test case for invalid examples and make sure that then output for globbed paths is the same as with the non-globbed counterparts (the ordering of files can be disregarded).

How do you suggest me to do this?

2022-06-15 07:38 UTC, codekie commented
I'd suggest, you create two mapping files, one with and one without globs, selecting the same files and use the same reference values to test against.

Btw. I really appreciate your efforts 👍. Thanks

2022-06-16 18:43 UTC, marc0l92 commented
I created the test you asked

2022-06-21 09:50 UTC, codekie requested changes
Just in case you made a force-push, please don't as GitHub can't automatically detect the changes since the last review.

2022-06-21 09:50 UTC, codekie commented on test/specs/impl/v2/index.js
> +                FILE_PATH__EXTERNAL_EXAMPLES_MAP_WITH_WILDCARDS);
Isn't this supposed to be `FILE_PATH__EXTERNAL_EXAMPLES_MAP_WITHOUT_WILDCARDS`?

2022-06-21 10:57 UTC, marc0l92 commented
> Just in case you made a force-push, please don't as GitHub can't automatically detect the changes since the last review.

Ok, in my company we try to limit the number of commits using push force, but I will not do it here

2022-06-21 11:43 UTC, codekie commented
The branch will be squashed to a single commit anyways when the pull request is merged, so it does not matter how many commits in the initial branch were 👍

2022-06-23 11:05 UTC, codekie approved these changes

2022-06-23 11:13 UTC, marc0l92 commented
You can merge

2022-06-23 11:19 UTC, merged