All properties required option #169
codekie/openapi-examples-validator pull request #173
Opened 2022-06-16 20:10 UTC by marc0l92

I made the code related to `--no-additional-properties` a bit more generic in order to reuse much of it in order to implement this feature.

It was not so difficult because the code is structured very well.

I will now work on the unit tests, but feel free to start taking a look at it if you have time.

2022-06-16 20:11 UTC, marc0l92 commented on src/impl/service/index.js
> +            value.required = Object.keys(value.properties);
This row is the only difference I have compared to `--no-additional-properties`

2022-06-21 10:00 UTC, codekie reviewed
Looks good to me so far.

2022-06-24 17:00 UTC, marc0l92 commented
I added a couple of tests for the `--all-properties-required` option (let me know if they are enough).
I also changed the way json combiner are detected by the `--no-additional-property` option in order to allow object that contains a property called `allOf` (see dedicated test).

I saw that you do some tests on `--no-additional-property` also in the file `test\specs\impl\v3\index.js` but not in the file `test\specs\impl\v2\index.js`. Can you suggest me what kind of test should I add in those files if any?

2022-06-29 08:31 UTC, codekie requested changes
In regards of the `v2`-tests, I'd suggest that you add one test that makes sure that the logic is called at all. The other cases should be covered by the `v3`-tests as they share the same code.

Good job 👍

2022-06-29 08:31 UTC, codekie commented on test/data/v3/additional-properties/schema-with-schema-combiner-as-property-invalid.yaml
> +                oneOf:
Please also add an `additionalProperties: false` test for one of the combiners within the hierarchy.

2022-07-07 12:05 UTC, codekie approved these changes
LGTM

Thanks again, for your contribution 👍

2022-07-07 12:09 UTC, merged